config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#omni_signin'

  resources :students do
    resources :notes
  end

  resources :notes

  resources :users do
    resources :students, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :students


end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    belongs_to :student
    validates :content, :created_at, :subject, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user #optional: true
    belongs_to :category
    has_many :notes
    has_many :users, through: :notes
    validates :first_name, :last_name, :birth_date, :grade_level, :career_goal, presence: true

    scope :alpha_order, -> { order(:last_name) }
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :students
    has_many :notes
    has_many :noted_students, through: :notes
    has_secure_password

    validates :username, :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :require_login
    helper_method :current_user, :user_authenticated

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_authenticated
        !!current_user
    end

    def require_login
        unless user_authenticated
            flash[:error] = "You Must Be logged in to access this page"
            redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @category = Category.all
    end

    def show
        @category = Category.find_by(id: params[:id])
        @category.students
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def index
        if params[:student_id] && @student = Student.find_by_id(params[:student_id])
            @notes = @student.notes
        else
            @error = "That Student Doesn't Exist" if params[:student_id]
            @notes = Note.all
        end
    end
    
    def new
        if params[:student_id] && @student = Student.find_by_id(params[:student_id])
            @note = @student.notes.build
        else
            @note = Note.new
        end 
    end

    def create
        @note = current_user.notes.build(note_params)
        if @note.save
            redirect_to notes_path
        else
            render :new
        end
    end

    def show
        @note = Note.find_by(id: params[:id])
    end

    def edit
        @note = Note.find_by(id: params[:id])
    end

    def update
        @note = Note.find_by(id: params[:id])
        if @note.update(note_params)
            redirect_to note_path(@note)
        else
            render :edit
        end
    end

    private

    def note_params
        params.require(:note).permit(:content, :created_at, :student_id, :user_id, :subject)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login, only: [:home, :new, :create, :omni_signin]

    def home
    end
    
    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:alert] = "Login Credentials Do Not Match Records"
            redirect_to "/login"
        end
    end

    def omni_signin
        @user = User.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |u|
            u.username = auth[:info][:name]
            u.email = auth[:info][:email]
            u.password = SecureRandom.hex(15)
        end
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to '/'
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    private 
    
    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def new
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @student = @user.students.build
        else
            @student = Student.new
        end
    end

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @students = @user.students.alpha_order
        else
            @students = Student.alpha_order
        end
    end

    def create
        @student = current_user.students.build(student_params)
        if @student.save
            redirect_to students_path
        else
            render :new
        end
    end

    def show
        @student = Student.find_by(id: params[:id])
    end

    def edit
        @student = Student.find_by_id(params[:id])
        if !@student || @student.user != current_user
            redirect_to students_path
            flash[:notice] = "You may not edit a student you didn't create"
        end
      end
    
      def update
         @student = Student.find_by(id: params[:id])
        redirect_to students_path if !@student || @student.user != current_user 

        if @student.update(student_params)
          redirect_to student_path(@student)
        else
          render :edit
          
        end
      end

    private

    def student_params
        params.require(:student).permit(:first_name, :last_name, :birth_date, :grade_level, :career_goal, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.includes(:students).find_by(id: params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/students_helper.rb
module StudentsHelper

    def index_display_header
        if @user
          content_tag(:h1, "#{@user.username}'s Students:")
        else
          content_tag(:h2, "All Students")
        end
      end

    def display_students
        if @user.students.empty?
            tag.h3(link_to('No Students, Create Here', new_student_path))
        else
            user = @user == current_user ? 'Your' : "#{@user.username}'s"
            content_tag(:h3, "#{user} #{pluralize(@user.students.count, 'Student')}:")
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuidanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
    <ul class="nav navbar-nav mr-auto">
      <% if user_authenticated %>
        <li class="nav-item"><%= link_to "Create New Student", new_student_path %></li>
        <li class="nav-item"><%= link_to "All Students", students_path %></li>
        <li class="nav-item"><%= link_to "My Students", user_students_path(current_user) %></li>
        <li class="nav-item"><%= link_to "Create Meeting Note", new_note_path %></li>
        <li class="nav-item"><%= link_to "All Meeting Notes", notes_path %></li>
        <li class="nav-item"><%= link_to "Home", user_path(current_user) %></li>
        <li class="nav-item"><%= link_to "Logout", logout_path, method: "delete" %></li>
      <% end %>
    </ul>
    </div>

    <div>
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>
      <%= @error %>
      <%= flash[:notice] if flash[:notice] %>
  
    </div>

    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @note} %>

<%= form_for([@note.student, @note]) do |f|%>
 <% if !@note.student %>
  <%= f.label :student %>:  
  <%= f.collection_select :student_id, Student.all, :id, :first_name %><br></br>
<% else %>
    <%= f.hidden_field :student_id %>
<% end %>
  <%= f.label :created_at, "Date" %>:
  <%= f.date_field :created_at %><br></br>
    <%= f.label :subject, "Meeting Subject" %>:
  <%= f.text_field :subject %><br></br>
  <%= f.label :content %>:
  <%= f.text_area :content, size:"70x8" %><br></br>
  <%= f.submit %><br>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit Your Meetings Note!<h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<% if @student %>
    <h1>Meeting Notes for <%= @student.first_name %> <%= @student.last_name %></h1>
<% else %>
    <h1>All Meeting Notes</h1>
<% end %>

<ul>
  <% @notes.each do |n| %>
    <li>
      <%= n.user.username %> submitted "<%= link_to n.subject, note_path(n) %>" on <strong><%= n.created_at.strftime("%m/%d/%Y")%></strong> for <%= link_to n.student.first_name, student_path(n.student_id) %>
    </li>
  <% end %>
</ul>

app/views/notes/new.html.erb
<h1>New Meeting Note!</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<h2><%= @note.subject%> - Submitted by:<%= @note.user.username%></h2> (<%= link_to "Edit Meeting Note", edit_note_path(@note) %>)
<p><strong>Date Submitted:</strong><%= @note.created_at.strftime("%A, %B %d, %Y") %></p>
<h4>Notes From Meeting:</h4>
<p><%= @note.content %></p>

<h4>View More Student Notes: <%= link_to @note.student.first_name, student_path(@note.student_id) %></h4>

app/views/students/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @student} %>

<%= form_for(@student) do |f| %>

    <%= f.label :first_name %>:
    <%= f.text_field :first_name %><br></br>

    <%= f.label :last_name %>:
    <%= f.text_field :last_name %><br></br>

    <%= f.label :birth_date %>:
    <%= f.date_field :birth_date %><br></br>

    <%= f.label :grade_level %>:
    <%= f.number_field :grade_level %><br></br>

    <%= f.label :career_goal %>:
    <%= f.text_field :career_goal %><br></br>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit %>

<% end %>

app/views/students/edit.html.erb
<h1>Edit <%= @student.first_name%> <%= @student.last_name %>!</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<%= index_display_header %>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
<Table>
  <tr>
      <th>Student Last Name</th>
       <th>Student First Name</th>
      <th>Advisor</th>
      <th>Total Meetings</th>
      <th>Student Page</th>
   </tr>

  <% @students.each do |s| %>
  
    <tr>
      <td><%= s.last_name.titleize %></td>
      <td><%= s.first_name.titleize %></td>
      <td><%= s.user.username.titleize %></td>
      <td><%= s.notes.count %> </td>
      <td><%= link_to "Got to Student Page", student_path(s) %></td>
     </tr> 
  <% end %>
</Table>

app/views/students/new.html.erb
<h1>Create A New Student: </h1>

<%= render 'form' %>  

app/views/students/show.html.erb
<h1><%= @student.last_name %>, <%= @student.first_name %> Information (<%= link_to "Edit Student", edit_student_path(@student) %>)</h1>
<p><strong>Student Grade:</strong> <%= @student.grade_level %> || <strong>Student DOB:</strong> <%= @student.birth_date.strftime("%m/%d/%Y") %> || <strong>Student Plan:</strong> <%= @student.career_goal %></p>
<p>Student Created By: <%= @student.user.username %></p>
<p><%= link_to "Add A New Meeting Note", new_student_note_path(@student)%></p>
<h4><%= link_to "View Meeting Notes", student_notes_path(@student) %></h4>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :email %>
    <%= f.email_field :email %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.submit "Submit" %> <%= link_to "Back", root_path %>

<% end %>

app/views/users/show.html.erb
<h1> Welcome <%= current_user.username.titleize %> </h1>

<h1><%= display_students %></h1> 
<ul>
    <% current_user.students.each do |s|%>
      <li><%= s.first_name %> <%= s.last_name%> (<%= link_to "Student Page", student_path(s) %>) </li>
    <% end %>
</ul>